# Generated by Django 2.1.3 on 2019-01-05 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('C', 'comment'), ('CP', 'comment-post'), ('L', 'like'), ('S', 'subscription')], max_length=20, verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_initiator', to=settings.AUTH_USER_MODEL, verbose_name='Initiator'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='readed',
            field=models.BooleanField(default=False, verbose_name='Readed'),
        ),
    ]
