# Generated by Django 2.1.3 on 2019-01-05 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialog_from_user', to=settings.AUTH_USER_MODEL, verbose_name='From user'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialog_to_user', to=settings.AUTH_USER_MODEL, verbose_name='To user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='message',
            name='data_publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data publish'),
        ),
        migrations.AlterField(
            model_name='message',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Dialog', verbose_name='Dialog'),
        ),
        migrations.AlterField(
            model_name='message',
            name='readed',
            field=models.BooleanField(default=False, verbose_name='Readed'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=300, verbose_name='Text'),
        ),
    ]
