# Generated by Django 2.1.3 on 2018-11-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20181126_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='name',
        ),
    ]
