# Generated by Django 2.1.3 on 2018-11-27 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_auto_20181127_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='to_user',
        ),
        migrations.AddField(
            model_name='dialog',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
