# Generated by Django 2.1.3 on 2018-11-27 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_auto_20181127_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='members',
        ),
        migrations.AddField(
            model_name='dialog',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialog_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dialog',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialog_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
