# Generated by Django 2.1.3 on 2019-01-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjaxLoaderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loader_url', models.URLField(max_length=120)),
                ('location', models.URLField(max_length=120, unique=True)),
                ('sort', models.CharField(max_length=30)),
                ('params', models.CharField(max_length=100)),
                ('paginate', models.IntegerField(default=10)),
            ],
        ),
    ]
