# Generated by Django 2.1.3 on 2019-01-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajaxloadermodel',
            name='loader_url',
        ),
        migrations.RemoveField(
            model_name='ajaxloadermodel',
            name='params',
        ),
        migrations.AddField(
            model_name='ajaxloadermodel',
            name='field',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ajaxloadermodel',
            name='location',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
