# Generated by Django 2.1.3 on 2019-01-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_utils', '0002_auto_20190109_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajaxloadermodel',
            name='top_field',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
