# Generated by Django 2.1.3 on 2019-01-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_utils', '0003_ajaxloadermodel_top_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajaxloadermodel',
            name='detail',
            field=models.BooleanField(default=False),
        ),
    ]
