# Generated by Django 2.1.3 on 2019-01-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_utils', '0004_ajaxloadermodel_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajaxloadermodel',
            name='type',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
