# Generated by Django 2.1.3 on 2019-01-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infomodel',
            old_name='text',
            new_name='html',
        ),
        migrations.RemoveField(
            model_name='infomodel',
            name='type_info',
        ),
        migrations.AddField(
            model_name='infomodel',
            name='url',
            field=models.URLField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
