# Generated by Django 2.1.3 on 2019-01-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190106_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
