# Generated by Django 2.1.3 on 2019-01-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.CharField(max_length=400, verbose_name='Question body'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=True, max_length=20, verbose_name='Question open'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Question title'),
        ),
    ]
