# Generated by Django 2.1.3 on 2019-01-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_infomodel_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='url',
            field=models.CharField(max_length=50),
        ),
    ]
