# Generated by Django 2.1.3 on 2018-12-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like_dislike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(choices=[('L', 'like'), ('S', 'subscribe')], default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribe',
            name='type',
            field=models.CharField(choices=[('L', 'like'), ('S', 'subscribe')], default='d', max_length=30),
            preserve_default=False,
        ),
    ]
