# Generated by Django 2.1.3 on 2018-12-12 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('like_dislike', '0002_remove_likedislike_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
