# Generated by Django 2.1.3 on 2018-12-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like_dislike', '0002_auto_20181229_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.CharField(choices=[('A', 'article'), ('C', 'comments'), ('U', 'user'), ('Com', 'community')], max_length=30),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='type',
            field=models.CharField(choices=[('A', 'article'), ('C', 'comments'), ('U', 'user'), ('Com', 'community')], max_length=30),
        ),
    ]
