# Generated by Django 2.1.3 on 2019-01-05 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('like_dislike', '0003_auto_20181229_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.CharField(choices=[('A', 'article'), ('C', 'comments'), ('U', 'user'), ('Com', 'community')], max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='type',
            field=models.CharField(choices=[('A', 'article'), ('C', 'comments'), ('U', 'user'), ('Com', 'community')], max_length=30, verbose_name='Type'),
        ),
    ]
