# Generated by Django 2.1.3 on 2018-12-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like_dislike', '0004_auto_20181212_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='followers',
            new_name='follower',
        ),
    ]
