# Generated by Django 2.1.3 on 2018-12-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like_dislike', '0005_auto_20181212_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='follower',
            new_name='user',
        ),
    ]
