# Generated by Django 2.1.3 on 2019-01-05 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banlist',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='Attempts'),
        ),
        migrations.AlterField(
            model_name='banlist',
            name='ban',
            field=models.BooleanField(default=False, verbose_name='Ban'),
        ),
        migrations.AlterField(
            model_name='banlist',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='banlist',
            name='time_unblock',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time unblock'),
        ),
    ]
