# Generated by Django 2.1.3 on 2018-11-18 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modify_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=266)),
                ('text', models.TextField(max_length=10024)),
                ('views', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('A', 'Active'), ('C', 'Close')], default='A', max_length=12)),
                ('author', models.ForeignKey(on_delete=models.SET('delete'), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modify_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=124)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modify_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=124)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
