# Generated by Django 2.1.3 on 2018-12-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('P', 'POST'), ('A', 'ARTICLE')], default='P', max_length=12),
        ),
    ]
