# Generated by Django 2.1.3 on 2018-12-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181202_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'POST'), ('A', 'ARTICLE')], max_length=12),
        ),
    ]
