# Generated by Django 2.1.3 on 2018-12-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_thread_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(upload_to='thread_img/'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='sub',
            field=models.CharField(max_length=124),
        ),
    ]
