# Generated by Django 2.1.3 on 2018-11-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181120_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=2024),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=324),
        ),
    ]
