# Generated by Django 2.1.3 on 2018-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181205_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='top',
        ),
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
