# Generated by Django 2.1.3 on 2018-12-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181230_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='last_modify_data',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='rating',
        ),
    ]
