# Generated by Django 2.1.3 on 2018-12-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181206_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(default='thread_img/thread_default.jpg', upload_to='thread_img/'),
        ),
    ]
