# Generated by Django 2.1.3 on 2018-12-04 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_article_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.ManyToManyField(null=True, related_name='article_set_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
