# Generated by Django 2.1.3 on 2019-01-05 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181230_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='community',
            name='rating',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Community', verbose_name='Community'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create data'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_img/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_modify_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last modify data'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'POST'), ('A', 'ARTICLE')], default='P', max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, max_length=2024, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=524, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='article_set_views', to=settings.AUTH_USER_MODEL, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='community',
            name='create_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create data'),
        ),
        migrations.AlterField(
            model_name='community',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='community',
            name='last_modify_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last modify data'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create data'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=44, unique=True, verbose_name='Name'),
        ),
    ]
