# Generated by Django 2.1.3 on 2019-01-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190105_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='community',
        ),
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
