# Generated by Django 2.1.3 on 2018-12-04 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181204_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='article_set_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
