# Generated by Django 2.1.3 on 2018-12-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181204_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='sub',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
