# Generated by Django 2.1.3 on 2018-12-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_thread_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
