# Generated by Django 2.1.3 on 2019-01-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190108_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, max_length=488, null=True, verbose_name='Text'),
        ),
    ]
