# Generated by Django 2.1.3 on 2018-12-04 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20181204_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='participant',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
