# Generated by Django 2.1.3 on 2018-12-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181216_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='active',
            new_name='is_active',
        ),
    ]
