# Generated by Django 2.1.3 on 2018-12-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='user_img/thumbnails/'),
            preserve_default=False,
        ),
    ]
