# Generated by Django 2.1.3 on 2018-12-25 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181224_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('time_unblock', models.DateTimeField(default=datetime.datetime(2018, 12, 25, 18, 56, 22, 512225, tzinfo=utc))),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='owner',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_img/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='user_img/thumbnails/'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
