# Generated by Django 2.1.3 on 2018-12-08 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bloguser_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='uniq_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(default='user_img/default_user_img.png', upload_to='user_img/'),
        ),
    ]
