# Generated by Django 2.1.3 on 2018-12-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='user_img/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_img/'),
        ),
    ]
