# Generated by Django 2.1.3 on 2018-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181124_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('friends', models.ManyToManyField(to='account.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='slug',
        ),
        migrations.AddField(
            model_name='bloguser',
            name='profile',
            field=models.OneToOneField(default=None, on_delete=True, to='account.Profile'),
            preserve_default=False,
        ),
    ]
