# Generated by Django 2.1.3 on 2018-12-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181208_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='uniq_uuid',
            new_name='uuid',
        ),
    ]
