# Generated by Django 2.1.3 on 2018-12-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181203_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='user_img/thumbnails/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(upload_to='user_img/'),
        ),
    ]
