# Generated by Django 2.1.3 on 2018-12-25 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181225_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banlist',
            name='time_unblock',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
