# Generated by Django 2.1.3 on 2018-11-25 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181125_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='followers',
            field=models.ManyToManyField(related_name='_bloguser_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='subscriptions',
            field=models.ManyToManyField(related_name='_bloguser_subscriptions_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='friends',
            field=models.ManyToManyField(related_name='_bloguser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
