# Generated by Django 2.1.3 on 2018-12-10 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181208_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='last_verify',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
