# Generated by Django 2.1.3 on 2018-11-25 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20181125_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='subscriptions',
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
