# Generated by Django 2.1.3 on 2018-12-26 18:04

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20181226_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_city',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
