# Generated by Django 2.1.3 on 2018-12-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_bloguser_last_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='followers',
        ),
    ]
