# Generated by Django 2.1.3 on 2018-12-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20181226_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BanList',
        ),
    ]
