# Generated by Django 2.1.3 on 2018-12-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='readed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('C', 'comment'), ('CP', 'comment-post'), ('L', 'like'), ('S', 'subscription')], max_length=20),
        ),
    ]
