# Generated by Django 2.1.3 on 2018-12-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_banlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='current_city',
            new_name='country',
        ),
    ]
