# Generated by Django 2.1.3 on 2019-01-05 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20181230_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is verified'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last activity'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Uuid'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bloguser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='head',
            field=models.ImageField(blank=True, help_text='You can upload an image in JPG or PNG formats. Max size file 2mb', null=True, upload_to='user_img/', verbose_name='Head'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, help_text='You can upload an image in JPG or PNG formats. Max size file 2mb', null=True, upload_to='user_img/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='user_img/thumbnails/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='User name'),
        ),
    ]
