# Generated by Django 2.1.3 on 2019-01-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_bloguser_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='geo',
            field=models.CharField(default='RU', max_length=100, verbose_name='User geo'),
        ),
    ]
