# Generated by Django 2.1.3 on 2018-12-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_head',
            field=models.ImageField(blank=True, null=True, upload_to='user_img/'),
        ),
    ]
