# Generated by Django 2.1.3 on 2018-12-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_user_head'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloguser',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
