# Generated by Django 2.1.3 on 2019-01-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190108_1653'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bloguser',
            managers=[
            ],
        ),
    ]
