# Generated by Django 2.1.3 on 2018-12-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20181222_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_head',
            new_name='head',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='login',
            new_name='name',
        ),
    ]
