# Generated by Django 2.1.3 on 2018-12-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20181214_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=424),
        ),
    ]
