# Generated by Django 2.1.3 on 2018-12-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='active',
            new_name='is_active',
        ),
    ]
